spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: 
server:
  servlet:
    context-path: /ex-beginner
